### PR TITLE
change manifest remove provider

### PR DESCRIPTION
**Pull request by rohanhc**
Provider was causing conflict and not letting you install main sudokuquest app if you had underground

### CODE REVIEW

**Comment by rampr** [comment]
Should this be present in both apps or only in underground ?

**Comment by jishnu7** [comment]
What all will be the problems of not having a ContentProvider?

**Comment by rohanhc** [comment]
https://developers.facebook.com/docs/reference/android/current/class/FacebookContentProvider/
Note that this ContentProvider is only necessary if an application wishes to attach images, etc., that are stored in memory and do not have another way to be referenced by a content URI. 

I tested everything. Requests, images, friends, etc. Doesn't seem to be any issue.

**Comment by rohanhc** [comment]
Yes @rampr going to push so that underground apps get checked out by only underground app

**Comment by rohanhc** [comment]
Removing it from our facebook plugin

**Pull request closed without merging**
